// frameworks/svelte/src/scenario-2/Row.svelte
<script>
import Cell from "./Cell.svelte";

export let columns;
let count = 0;
let offset = 0;

function onInput() {
    count += 1;
}
function updateRow() {
    offset += 1;
}

</script>

  <div>
    <div>
      Row count: { count }
      <button class="row-btn-update-children" on:click="{updateRow}">
        Update children
      </button>
      <button class="row-btn-update-self" on:click="{onInput}">Upate parent</button>
    </div>
    {#each columns as column, i (column.id)}
        <Cell value="{i + offset}" />
    {/each}    
  </div>

// frameworks/angular/src/app/scenario-2/row.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'row',
  templateUrl: './row.component.html',
})
export class Row {
  @Input() columns: any[];

  count = 0;
  offset = 0;

  onInput() {
    this.count += 1;
  }
  updateRow() {
    this.offset += 1;
  }
  trackBy(item) {
    return item.id;
  }
}

<div>
  <div>
    Row count: {{ count }}
    <button class="row-btn-update-children" (click)="updateRow()">
      Update children
    </button>
    <button class="row-btn-update-self" (click)="onInput()">
      Upate parent
    </button>
  </div>
  <cell
    *ngFor="let column of columns; index as i; trackBy: trackBy"
    [value]="i + offset"
  ></cell>
</div>
