// frameworks/svelte/src/scenario-2/Scenario2.svelte

<div>
  <div>
    <label>Number of rows</label>
    <input
      id="input-rows"
      type="number"
      min="1"
      on:change="{(event) => onUpdateRows(event.target.value)}"
    />
    <label>Number of columns</label>
    <input
      id="input-columns"
      type="number"
      min="1"
      on:change="{(event) => onUpdateColumns(event.target.value)}"
    />
    <button id="btn-generate" on:click="{generate}">
      Generate
    </button>
  </div>
  <div>
  {#each rows as row (row.id)}
    <Row columns="{row.columns}" />
  {/each}
  </div>
</div>

<script>
import Row from "./Row.svelte";

let numRows = 0;
let numColumns = 0;
let rows = [];

function generate() {
  rows = new Array(numRows).fill(null).map((_, i) => ({
    id: i,
    columns: new Array(numColumns).fill(null).map((_, y) => ({
      id: `row${i}-col${y}`,
    })),
  }));
}

function onUpdateColumns(value) {
  numColumns = parseInt(value, 10);
} function onUpdateRows(value) {
  numRows = parseInt(value, 10);
}
  
</script>

// frameworks/angular/src/app/scenario-2/scenario2.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'scenario2',
  templateUrl: './scenario2.component.html',
})
export class Scenario2 {
  numRows = 0;
  numColumns = 0;
  rows = [];

  generate() {
    this.rows = new Array(this.numRows).fill(null).map((_, i) => ({
      id: i,
      columns: new Array(this.numColumns).fill(null).map((_, y) => ({
        id: `row${i}-col${y}`,
      })),
    }));
  }

  onUpdateColumns(event) {
    this.numColumns = parseInt(event.target.value, 10);
  }

  onUpdateRows(event) {
    this.numRows = parseInt(event.target.value, 10);
  }

  trackBy(item) {
    return item.id;
  }
}

<div>
  <div>
    <label>Number of rows</label>
    <input
      id="input-rows"
      type="number"
      min="1"
      (change)="onUpdateRows($event)"
    />
    <label>Number of columns</label>
    <input
      id="input-columns"
      type="number"
      min="1"
      (change)="onUpdateColumns($event)"
    />
    <button id="btn-generate" (click)="generate()">Generate</button>
  </div>
  <div>
    <row
      *ngFor="let row of rows; trackBy: trackBy"
      [columns]="row.columns"
    ></row>
  </div>
</div>
