// frameworks/svelte/src/App.svelte
<script>
  import Scenario1 from "./scenario-1/Scenario1.svelte";
  import Scenario2 from "./scenario-2/Scenario2.svelte";
  import Scenario3 from "./scenario-3/Scenario3.svelte";
  import Scenario4 from './scenario-4/Scenario4.svelte';

  function selectScenario(value) {
    selectedScenario = value;
  }
  let selectedScenario = null;
  $: scenarioComponent =
    selectedScenario === 1
      ? Scenario1
      : selectedScenario === 2
      ? Scenario2
      : selectedScenario === 3
      ? Scenario3
      : selectedScenario === 4
      ? Scenario4
      : null;
</script>

<main>
  <div>
    {#if selectedScenario == null}
      <div>
        <h4>Select scenario</h4>
        <div>
          <div>
            <label>
              Scenario 1: Generate and delete components
            </label>
            <button id="btn-scen-1" on:click={() => selectScenario(1)}>
              Select
            </button>
          </div>
          <div>
            <label>
              Scenario 2: Update components in a flat DOM tree
              <button id="btn-scen-2" on:click={() => selectScenario(2)}>
                Select
              </button>
            </label>
          </div>
          <div>
            <label>
              Scenario 3: Update components in a branching DOM tree
              <button id="btn-scen-3" on:click={() => selectScenario(3)}>
                Select
              </button>
            </label>
          </div>
          <div>
          <label>
            Scenario 4: Update components containing mostly static content
            <button id="btn-scen-4" on:click="{() => selectScenario(4)}">Select</button>
          </label>
        </div>
        </div>
      </div>
    {:else}
      <svelte:component this={scenarioComponent} />
    {/if}
  </div>
</main>

// frameworks/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  selectedScenario = null;

  selectScenario(value) {
    this.selectedScenario = parseInt(value, 10);
  }
}

<div>
  <div *ngIf="!selectedScenario">
    <h4>Select scenario</h4>
    <div>
      <div>
        <label>Scenario 1: Generate and delete components </label>
        <button id="btn-scen-1" (click)="selectScenario(1)">Select</button>
      </div>
      <div>
        <label>
          Scenario 2: Update components in a flat DOM tree
          <button id="btn-scen-2" (click)="selectScenario(2)">Select</button>
        </label>
      </div>
      <div>
        <label>
          Scenario 3: Update components in a branching DOM tree
          <button id="btn-scen-3" (click)="selectScenario(3)">Select</button>
        </label>
      </div>
      <div>
        <label>
          Scenario 4: Update components containing mostly static content
          <button id="btn-scen-4" (click)="selectScenario(4)">Select</button>
        </label>
      </div>
    </div>
  </div>
  <scenario1 *ngIf="selectedScenario === 1"></scenario1>
  <scenario2 *ngIf="selectedScenario === 2"></scenario2>
  <scenario3 *ngIf="selectedScenario === 3"></scenario3>
  <scenario4 *ngIf="selectedScenario === 4"></scenario4>
</div>
