// frameworks/react/src/scenario-6/Node.js
import React from "react";

export default class Node extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
    };
  }

  increment() {
    this.setState({
      count: this.state.count + 1,
    });
  }

  render() {
    return (
      <div>
        {this.props.items.map((item, i) => (
          <div key={i}>
            <span>{item.value0}</span>
            <span>{item.value1}</span>
            <span>{item.value2}</span>
            <span>{item.value3}</span>
            <span>{item.value4}</span>
            <span>{item.value5}</span>
            <span>{item.value6}</span>
            <span>{item.value7}</span>
            <span>{item.value8}</span>
            <span>{item.value9}</span>
          </div>
        ))}
        <div>
          {this.state.count}
          <button
            className="btn-increment-leaf"
            onClick={() => this.increment()}
          >
            Update
          </button>
        </div>
        {this.props.subtreeDepth > 0
          ? [...Array(this.props.branchingFactor)].map((_, i) => (
              <Node
                key={i}
                branchingFactor={this.props.branchingFactor}
                subtreeDepth={this.props.subtreeDepth - 1}
                items={this.props.items}
              />
            ))
          : null}
      </div>
    );
  }
}

// frameworks/angular/src/app/scenario-6/node.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sc6-node',
  templateUrl: './node.component.html',
})
export class Scenario6Node {
  @Input() branches: number[];
  @Input() subtreeDepth: number;

  count = 0;
  items = Array(10)
    .fill(null)
    .map((_, i) => ({
      id: i,
      nested: {
        nested: {
          nested: {
            nested: {
              nested: {
                nested: {
                  nested: {
                    nested: {
                      nested: {
                        nested: {
                          value0: 0,
                          value1: 1,
                          value2: 2,
                          value3: 3,
                          value4: 4,
                          value5: 5,
                          value6: 6,
                          value7: 7,
                          value8: 8,
                          value9: 9,
                        },

                        value0: 0,
                        value1: 1,
                        value2: 2,
                        value3: 3,
                        value4: 4,
                        value5: 5,
                        value6: 6,
                        value7: 7,
                        value8: 8,
                        value9: 9,
                      },

                      value0: 0,
                      value1: 1,
                      value2: 2,
                      value3: 3,
                      value4: 4,
                      value5: 5,
                      value6: 6,
                      value7: 7,
                      value8: 8,
                      value9: 9,
                    },

                    value0: 0,
                    value1: 1,
                    value2: 2,
                    value3: 3,
                    value4: 4,
                    value5: 5,
                    value6: 6,
                    value7: 7,
                    value8: 8,
                    value9: 9,
                  },
                  value0: 0,
                  value1: 1,
                  value2: 2,
                  value3: 3,
                  value4: 4,
                  value5: 5,
                  value6: 6,
                  value7: 7,
                  value8: 8,
                  value9: 9,
                },
                value0: 0,
                value1: 1,
                value2: 2,
                value3: 3,
                value4: 4,
                value5: 5,
                value6: 6,
                value7: 7,
                value8: 8,
                value9: 9,
              },
              value0: 0,
              value1: 1,
              value2: 2,
              value3: 3,
              value4: 4,
              value5: 5,
              value6: 6,
              value7: 7,
              value8: 8,
              value9: 9,
            },
            value0: 0,
            value1: 1,
            value2: 2,
            value3: 3,
            value4: 4,
            value5: 5,
            value6: 6,
            value7: 7,
            value8: 8,
            value9: 9,
          },
          value0: 0,
          value1: 1,
          value2: 2,
          value3: 3,
          value4: 4,
          value5: 5,
          value6: 6,
          value7: 7,
          value8: 8,
          value9: 9,
        },
        value0: 0,
        value1: 1,
        value2: 2,
        value3: 3,
        value4: 4,
        value5: 5,
        value6: 6,
        value7: 7,
        value8: 8,
        value9: 9,
      },
      value0: 0,
      value1: 1,
      value2: 2,
      value3: 3,
      value4: 4,
      value5: 5,
      value6: 6,
      value7: 7,
      value8: 8,
      value9: 9,
    }));

  increment() {
    this.count += 1;
  }

  trackBy(item) {
    return item.id;
  }
}

<div>
  <div *ngFor="let item of items; trackBy: trackBy">
    <span>{{ item.value0 }}</span
    ><span>{{ item.value1 }}</span
    ><span>{{ item.value2 }}</span
    ><span>{{ item.value3 }}</span
    ><span>{{ item.value4 }}</span
    ><span>{{ item.value5 }}</span
    ><span>{{ item.value6 }}</span
    ><span>{{ item.value7 }}</span
    ><span>{{ item.value8 }}</span
    ><span>{{ item.value9 }}</span>
  </div>

  <div>
    {{ count }}
    <button class="btn-increment-leaf" (click)="increment()">
      Update leaf
    </button>
  </div>
  <ng-template [ngIf]="subtreeDepth > 0">
    <div>
      <sc6-node
        *ngFor="let branch of branches"
        [branches]="branches"
        [subtreeDepth]="subtreeDepth - 1"
      ></sc6-node>
    </div>
  </ng-template>
</div>
