// frameworks/vue3/src/components/scenario-3/Node2.vue
<template>
  <div>
    <template v-if="subtreeDepth > 0">
      <Node2
        v-for="n in branchingFactor"
        :key="n"
        :subtree-depth="subtreeDepth - 1"
        :branching-factor="branchingFactor"
      />
    </template>
    -
  </div>
</template>

<script>
export default {
  name: "Node2",
  props: {
    branchingFactor: {
      type: Number,
      required: true,
    },
    subtreeDepth: {
      type: Number,
      required: true,
    },
  },
};
</script>

// frameworks/react/src/scenario-3/Node2.js
import React from "react";

export default class Node2 extends React.Component {
  render() {
    return (
      <div>
        {this.props.subtreeDepth > 0
          ? [...Array(this.props.branchingFactor)].map((_, i) => (
              <Node2
                key={i}
                branchingFactor={this.props.branchingFactor}
                subtreeDepth={this.props.subtreeDepth - 1}
              />
            ))
          : null}
        -
      </div>
    );
  }
}
