// frameworks/svelte/src/scenario-3/Scenario3.svelte
<script>
  import Node from "./Node.svelte";
  import Node2 from "./Node2.svelte";

  let branchingFactor = 0;
  let treeDepth = 0;
  let initialized = false;
  let count = 0;
  let nodeType = 0;

  function onUpdateBranchingFactor(event) {
    branchingFactor = parseInt(event.target.value, 10);
  }
  function onUpdateTreeDepth(event) {
    treeDepth = parseInt(event.target.value, 10);
  }
  function generate() {
    initialized = true;
  }
  function generateSimple() {
    nodeType = 2;
    initialized = true;
  }
  function increment() {
    count += 1;
  }
</script>

<div>
  <label>Select branching factor</label>
  <input
    id="input-branching-factor"
    :value="branchingFactor"
    on:change={onUpdateBranchingFactor}
  />
  <label>Select tree depth</label>
  <input
    id="input-tree-depth"
    :value="treeDepth"
    on:change={onUpdateTreeDepth}
  />
  <button id="btn-generate" on:click={generate}>Generate tree</button>
  <button id="btn-generate-simple" on:click={generateSimple}
    >Generate simpler component tree</button
  >
  <div>{count}</div>
  <button id="btn-increment-root" on:click={increment}>Update root</button>
  {#if initialized}
    {#if nodeType === 1}
      <div>
        {#each Array(branchingFactor) as _}
          <Node {branchingFactor} subtreeDepth={treeDepth - 1} />
        {/each}
      </div>
    {:else}
      <div>
        {#each Array(branchingFactor) as _}
          <Node2 {branchingFactor} subtreeDepth={treeDepth - 1} />
        {/each}
      </div>
    {/if}
  {/if}
</div>

// frameworks/vue3/src/components/scenario-3/Scenario3.vue
<template>
  <div>
    <label>Select branching factor</label>
    <input
      id="input-branching-factor"
      type="number"
      :value="branchingFactor"
      @change="onUpdateBranchingFactor"
    />
    <label>Select tree depth</label>
    <input
      id="input-tree-depth"
      type="number'"
      :value="treeDepth"
      @change="onUpdateTreeDepth"
    />
    <button id="btn-generate" @click="generate">Generate tree</button>
    <button id="btn-generate-simple" @click="generateSimple">
      Generate simpler component tree
    </button>
    <div>{{ count }}</div>
    <button id="btn-increment-root" @click="increment">Update root</button>
    <div v-if="initialized">
      <template v-if="nodeType === 1">
        <Node
          v-for="n in branchingFactor"
          :key="n"
          :branching-factor="branchingFactor"
          :subtree-depth="treeDepth - 1"
        />
      </template>
      <template v-else>
        <Node2
          v-for="n in branchingFactor"
          :key="n"
          :branching-factor="branchingFactor"
          :subtree-depth="treeDepth - 1"
        />
      </template>
    </div>
  </div>
</template>

<script>
import Node from "./Node";
import Node2 from "./Node2";

export default {
  components: {
    Node,
    Node2,
  },
  data() {
    return {
      branchingFactor: 0,
      treeDepth: 0,
      initialized: false,
      count: 0,
      nodeType: 1,
    };
  },
  methods: {
    onUpdateBranchingFactor(event) {
      this.branchingFactor = parseInt(event.target.value, 10);
    },
    onUpdateTreeDepth(event) {
      this.treeDepth = parseInt(event.target.value, 10);
    },
    generate() {
      this.initialized = true;
    },
    generateSimple() {
      this.nodeType = 2;
      this.initialized = true;
    },
    increment() {
      this.count += 1;
    },
  },
};
</script>
