// frameworks/angular/src/app/scenario-2/cell.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'cell',
  templateUrl: './cell.component.html',
})
export class Cell {
  @Input() value: number;

  count = 0;

  increment() {
    this.count += 1;
  }
}

<span
  >Prop value: {{ value }}, internal value: {{ count }}
  <button class="cell-btn-increment" (click)="increment()">
    Update child
  </button></span
>

// frameworks/vue/src/components/scenario-2/Cell.vue
<template>
  <span
    >Prop value: {{ value }}, internal value: {{ count }}
    <button class="cell-btn-increment" @click="increment">
      Update child
    </button></span
  >
</template>

<script>
export default {
  props: {
    value: {
      type: Number,
      required: true,
    },
  },
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    increment() {
      this.count += 1;
    },
  },
};
</script>
