// frameworks/svelte/src/scenario-3/Scenario3.svelte
<script>
  import Node from "./Node.svelte";
  import Node2 from "./Node2.svelte";

  let branchingFactor = 0;
  let treeDepth = 0;
  let initialized = false;
  let count = 0;
  let nodeType = 0;

  function onUpdateBranchingFactor(event) {
    branchingFactor = parseInt(event.target.value, 10);
  }
  function onUpdateTreeDepth(event) {
    treeDepth = parseInt(event.target.value, 10);
  }
  function generate() {
    initialized = true;
  }
  function generateSimple() {
    nodeType = 2;
    initialized = true;
  }
  function increment() {
    count += 1;
  }
</script>

<div>
  <label>Select branching factor</label>
  <input
    id="input-branching-factor"
    :value="branchingFactor"
    on:change={onUpdateBranchingFactor}
  />
  <label>Select tree depth</label>
  <input
    id="input-tree-depth"
    :value="treeDepth"
    on:change={onUpdateTreeDepth}
  />
  <button id="btn-generate" on:click={generate}>Generate tree</button>
  <button id="btn-generate-simple" on:click={generateSimple}
    >Generate simpler component tree</button
  >
  <div>{count}</div>
  <button id="btn-increment-root" on:click={increment}>Update root</button>
  {#if initialized}
    {#if nodeType === 1}
      <div>
        {#each Array(branchingFactor) as _}
          <Node {branchingFactor} subtreeDepth={treeDepth - 1} />
        {/each}
      </div>
    {:else}
      <div>
        {#each Array(branchingFactor) as _}
          <Node2 {branchingFactor} subtreeDepth={treeDepth - 1} />
        {/each}
      </div>
    {/if}
  {/if}
</div>

// frameworks/angular/src/app/scenario-3/scenario3.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'scenario3',
  templateUrl: './scenario3.component.html',
})
export class Scenario3 {
  branchingFactor = 0;
  branches = [];
  treeDepth = 0;
  initialized = false;
  count = 0;
  nodeType = 1;

  onUpdateBranchingFactor(event) {
    this.branchingFactor = parseInt(event.target.value, 10);
    this.branches = Array(this.branchingFactor)
      .fill(null)
      .map((_, i) => i);
  }
  onUpdateTreeDepth(event) {
    this.treeDepth = parseInt(event.target.value, 10);
  }
  generate() {
    this.initialized = true;
  }
  generateSimple() {
    this.nodeType = 2;
    this.initialized = true;
  }
  increment() {
    this.count += 1;
  }
}

<div>
  <label>Select branching factor</label>
  <input
    id="input-branching-factor"
    type="number"
    (change)="onUpdateBranchingFactor($event)"
  />
  <label>Select tree depth</label>
  <input
    id="input-tree-depth"
    type="number"
    (change)="onUpdateTreeDepth($event)"
  />
  <button id="btn-generate" (click)="generate()">Generate tree</button>
  <button id="btn-generate-simple" (click)="generateSimple()">
    Generate simpler component tree
  </button>
  <div>{{ count }}</div>
  <button id="btn-increment-root" (click)="increment()">Update root</button>
  <div *ngIf="initialized && nodeType === 1">
    <node
      *ngFor="let branch of branches"
      [branches]="branches"
      [subtreeDepth]="treeDepth - 1"
    ></node>
  </div>
  <div *ngIf="initialized && nodeType === 2">
    <node2
      *ngFor="let branch of branches"
      [branches]="branches"
      [subtreeDepth]="treeDepth - 1"
    ></node2>
  </div>
</div>
