// frameworks/svelte/src/scenario-5/Scenario5.svelte
<script>
  import Node from "./Node.svelte";

  let branchingFactor = 0;
  let treeDepth = 0;
  let initialized = false;
  let count = 0;
  let prop = 0;

  function onUpdateBranchingFactor(event) {
    branchingFactor = parseInt(event.target.value, 10);
  }
  function onUpdateTreeDepth(event) {
    treeDepth = parseInt(event.target.value, 10);
  }
  function generate() {
    initialized = true;
  }
  function increment() {
    count += 1;
  }
  function updateTree() {
    prop += 1;
  }
</script>

<div>
  <label>Select branching factor</label>
  <input
    id="input-branching-factor"
    :value="branchingFactor"
    on:change={onUpdateBranchingFactor}
  />
  <label>Select tree depth</label>
  <input
    id="input-tree-depth"
    :value="treeDepth"
    on:change={onUpdateTreeDepth}
  />
  <button id="btn-generate" on:click={generate}>Generate tree</button>
  <div>{count}</div>
  <button id="btn-increment-root" on:click={increment}>Update root</button>
  <button id="btn-update-tree" on:click={updateTree}>Update entire tree</button>
  {#if initialized}
    <div>
      {#each Array(branchingFactor) as _}
        <Node {branchingFactor} subtreeDepth={treeDepth - 1} {prop} />
      {/each}
    </div>
  {/if}
</div>

// frameworks/angular/src/app/scenario-5/scenario5.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'scenario5',
  templateUrl: './scenario5.component.html',
})
export class Scenario5 {
  branchingFactor = 0;
  branches = [];
  treeDepth = 0;
  initialized = false;
  count = 0;
  prop = 0;

  onUpdateBranchingFactor(event) {
    this.branchingFactor = parseInt(event.target.value, 10);
    this.branches = Array(this.branchingFactor)
      .fill(null)
      .map((_, i) => i);
  }
  onUpdateTreeDepth(event) {
    this.treeDepth = parseInt(event.target.value, 10);
  }
  generate() {
    this.initialized = true;
  }
  increment() {
    this.count += 1;
  }
  updateTree() {
    this.prop += 1;
  }
}

<div>
  <label>Select branching factor</label>
  <input
    id="input-branching-factor"
    type="number"
    (change)="onUpdateBranchingFactor($event)"
  />
  <label>Select tree depth</label>
  <input
    id="input-tree-depth"
    type="number"
    (change)="onUpdateTreeDepth($event)"
  />
  <button id="btn-generate" (click)="generate()">Generate tree</button>
  <div>{{ count }}</div>
  <button id="btn-increment-root" (click)="increment()">Update root</button>
  <button id="btn-update-tree" (click)="updateTree()">
    Update entire tree
  </button>
  <div *ngIf="initialized">
    <sc5-node
      *ngFor="let branch of branches"
      [branches]="branches"
      [subtreeDepth]="treeDepth - 1"
      [prop]="prop"
    ></sc5-node>
  </div>
</div>
