// frameworks/svelte/src/scenario-4/Scenario4.svelte
<script>
  import Child from "./Child.svelte";

  let numStuff = 0;
  let numChildren = 0;
  let offset = 0;
  $: children = new Array(numChildren).fill(null).map((_, i) => ({ id: i, value: i + offset }));

  function generate() {
    numChildren = numStuff;
  }

  function onChange(value) {
    numStuff = parseInt(value, 10);
  }

  function update() {
    offset += 1;
  }

  function updateSingle() {
    const i = Math.floor(Math.random() * Math.floor(children.length));
    children[i].value += 1;
  }
</script>

<div>
  <div>
    <div>
      <label>Number of components</label>
      <input
        id="input-components"
        type="number"
        min="1"
        :value="numChildren"
        on:change={(event) => onChange(event.target.value)}
      />
      <button id="btn-generate" on:click={generate}>
        Generate
      </button>
      <button id="btn-update" on:click={update}>Update children</button>
      <button id="btn-update-single" on:click={updateSingle}>
        Update single child
      </button>
    </div>
    {#each children as child (child.id)}
      <Child value={child.value} />
    {/each}
  </div>
</div>

// frameworks/vue/src/components/scenario-4/Scenario4.vue
<template>
  <div>
    <div>
      <label>Number of components</label>
      <input
        id="input-components"
        type="number"
        min="1"
        :value="numChildren"
        @change="onChange"
      />
      <button id="btn-generate" @click="generate">
        Generate
      </button>
      <button id="btn-update" @click="update">Update children</button>
      <button id="btn-update-single" @click="updateSingle">
        Update single child
      </button>
    </div>
    <Child v-for="child in children" :key="child.id" :value="child.value" />
  </div>
</template>

<script>
import Child from "./Child.vue";

export default {
  components: {
    Child,
  },
  data() {
    return {
      numChildren: 0,
      children: [],
    };
  },
  methods: {
    generate() {
      this.children = this.children = new Array(this.numChildren)
        .fill(null)
        .map((_, i) => ({ id: i, value: i }));
    },
    update() {
      this.children = this.children.map((child) => ({
        ...child,
        value: (child.value += 1),
      }));
    },
    updateSingle() {
      const i = Math.floor(Math.random() * Math.floor(this.children.length));
      this.children[i].value += 1;
    },
    onChange(event) {
      this.numChildren = parseInt(event.target.value, 10);
    },
  },
};
</script>
