// frameworks/vue3/src/components/scenario-3/Node.vue
<template>
  <div>
    <template v-if="subtreeDepth > 0">
      <Node
        v-for="n in branchingFactor"
        :key="n"
        :subtree-depth="subtreeDepth - 1"
        :branching-factor="branchingFactor"
      />
    </template>
    <div v-else>
      {{ count }}
      <button class="btn-increment-leaf" @click="increment">Update leaf</button>
    </div>
  </div>
</template>

<script>
export default {
  name: "Node",
  props: {
    branchingFactor: {
      type: Number,
      required: true,
    },
    subtreeDepth: {
      type: Number,
      required: true,
    },
  },
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    increment() {
      this.count += 1;
    },
  },
};
</script>

// frameworks/svelte/src/scenario-5/Node.svelte
<script>
  export let branchingFactor;
  export let subtreeDepth;
  let count = 0;

  function increment() {
    count += 1;
  }
</script>

<div>
  <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span />
  <div>
    {count}
    <button class="btn-increment-node" on:click={increment}>Update leaf</button>
  </div>
  <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span />
  {#if subtreeDepth > 0}
    {#each Array(branchingFactor) as _}
      <svelte:self subtreeDepth={subtreeDepth - 1} {branchingFactor} />
    {/each}
  {/if}
</div>
