// frameworks/react/src/scenario-5/Node.js
import React from "react";

export default class Node extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
    };
  }

  increment() {
    this.setState({
      count: this.state.count + 1,
    });
  }

  render() {
    return (
      <div>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <div>
          {this.state.count}
          <button
            className="btn-increment-leaf"
            onClick={() => this.increment()}
          >
            Update
          </button>
        </div>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        <span>-</span>
        {this.props.subtreeDepth > 0
          ? [...Array(this.props.branchingFactor)].map((_, i) => (
              <Node
                key={i}
                branchingFactor={this.props.branchingFactor}
                subtreeDepth={this.props.subtreeDepth - 1}
              />
            ))
          : null}
      </div>
    );
  }
}

// frameworks/svelte/src/scenario-5/Node.svelte
<script>
  export let branchingFactor;
  export let subtreeDepth;
  let count = 0;

  function increment() {
    count += 1;
  }
</script>

<div>
  <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span />
  <div>
    {count}
    <button class="btn-increment-node" on:click={increment}>Update leaf</button>
  </div>
  <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span>-</span><span>-</span><span>-</span><span
    >-</span
  ><span>-</span><span>-</span><span />
  {#if subtreeDepth > 0}
    {#each Array(branchingFactor) as _}
      <svelte:self subtreeDepth={subtreeDepth - 1} {branchingFactor} />
    {/each}
  {/if}
</div>
