// frameworks/vue/src/components/scenario-5/Scenario5.vue
<template>
  <div>
    <label>Select branching factor</label>
    <input
      id="input-branching-factor"
      type="number"
      :value="branchingFactor"
      @change="onUpdateBranchingFactor"
    />
    <label>Select tree depth</label>
    <input
      id="input-tree-depth"
      type="number'"
      :value="treeDepth"
      @change="onUpdateTreeDepth"
    />
    <button id="btn-generate" @click="generate">Generate tree</button>
    <div>{{ count }}</div>
    <button id="btn-increment-root" @click="increment">Update root</button>
    <button id="btn-update-tree" @click="updateTree">Update entire tree</button>
    <div v-if="initialized">
      <Node
        v-for="n in branchingFactor"
        :key="n"
        :branching-factor="branchingFactor"
        :subtree-depth="treeDepth - 1"
        :prop="prop"
      />
    </div>
  </div>
</template>

<script>
import Node from "./Node";

export default {
  components: {
    Node,
  },
  data() {
    return {
      branchingFactor: 0,
      treeDepth: 0,
      initialized: false,
      count: 0,
      prop: 0,
    };
  },
  methods: {
    onUpdateBranchingFactor(event) {
      this.branchingFactor = parseInt(event.target.value, 10);
    },
    onUpdateTreeDepth(event) {
      this.treeDepth = parseInt(event.target.value, 10);
    },
    generate() {
      this.initialized = true;
    },
    increment() {
      this.count += 1;
    },
    updateTree() {
      this.prop += 1;
    },
  },
};
</script>

// frameworks/svelte/src/scenario-5/Scenario5.svelte
<script>
  import Node from "./Node.svelte";

  let branchingFactor = 0;
  let treeDepth = 0;
  let initialized = false;
  let count = 0;
  let prop = 0;

  function onUpdateBranchingFactor(event) {
    branchingFactor = parseInt(event.target.value, 10);
  }
  function onUpdateTreeDepth(event) {
    treeDepth = parseInt(event.target.value, 10);
  }
  function generate() {
    initialized = true;
  }
  function increment() {
    count += 1;
  }
  function updateTree() {
    prop += 1;
  }
</script>

<div>
  <label>Select branching factor</label>
  <input
    id="input-branching-factor"
    :value="branchingFactor"
    on:change={onUpdateBranchingFactor}
  />
  <label>Select tree depth</label>
  <input
    id="input-tree-depth"
    :value="treeDepth"
    on:change={onUpdateTreeDepth}
  />
  <button id="btn-generate" on:click={generate}>Generate tree</button>
  <div>{count}</div>
  <button id="btn-increment-root" on:click={increment}>Update root</button>
  <button id="btn-update-tree" on:click={updateTree}>Update entire tree</button>
  {#if initialized}
    <div>
      {#each Array(branchingFactor) as _}
        <Node {branchingFactor} subtreeDepth={treeDepth - 1} {prop} />
      {/each}
    </div>
  {/if}
</div>
