// frameworks/react/src/scenario-3/Node.js
import React from "react";

export default class Node extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
    };
  }

  increment() {
    this.setState({
      count: this.state.count + 1,
    });
  }

  render() {
    return (
      <div>
        {this.props.subtreeDepth > 0 ? (
          [...Array(this.props.branchingFactor)].map((_, i) => (
            <Node
              key={i}
              branchingFactor={this.props.branchingFactor}
              subtreeDepth={this.props.subtreeDepth - 1}
            />
          ))
        ) : (
          <div>
            {this.state.count}
            <button
              className="btn-increment-leaf"
              onClick={() => this.increment()}
            >
              Update leaf
            </button>
          </div>
        )}
      </div>
    );
  }
}

// frameworks/svelte/src/scenario-3/Node.svelte

  <div>
    {#if subtreeDepth > 0}
        {#each Array(branchingFactor) as _ }
            <svelte:self
                subtreeDepth="{subtreeDepth - 1}"
                branchingFactor="{branchingFactor}" />
        {/each}
    {:else}
    <div>
        { count }
        <button class="btn-increment-leaf" on:click="{increment}">Update leaf</button>
    </div>
    {/if}
  </div>

<script>
export let branchingFactor;
export let subtreeDepth;
let count = 0;

function increment() {
    count += 1; 
}
</script>
