// frameworks/vue/src/components/scenario-2/Row.vue
<template>
  <div>
    <div>
      Row count: {{ count }}
      <button class="row-btn-update-children" @click="updateRow">
        Update children
      </button>
      <button class="row-btn-update-self" @click="onInput">Upate parent</button>
    </div>
    <Cell v-for="(col, i) in columns" :key="col.id" :value="i + offset" />
  </div>
</template>

<script>
import Cell from "./Cell";

export default {
  components: {
    Cell,
  },
  props: {
    columns: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      count: 0,
      offset: 0,
    };
  },
  methods: {
    onInput() {
      this.count += 1;
    },
    updateRow() {
      this.offset += 1;
    },
  },
};
</script>

// frameworks/svelte/src/scenario-2/Row.svelte
<script>
import Cell from "./Cell.svelte";

export let columns;
let count = 0;
let offset = 0;

function onInput() {
    count += 1;
}
function updateRow() {
    offset += 1;
}

</script>

  <div>
    <div>
      Row count: { count }
      <button class="row-btn-update-children" on:click="{updateRow}">
        Update children
      </button>
      <button class="row-btn-update-self" on:click="{onInput}">Upate parent</button>
    </div>
    {#each columns as column, i (column.id)}
        <Cell value="{i + offset}" />
    {/each}    
  </div>
