// frameworks/vue/src/components/scenario-2/Cell.vue
<template>
  <span
    >Prop value: {{ value }}, internal value: {{ count }}
    <button class="cell-btn-increment" @click="increment">
      Update child
    </button></span
  >
</template>

<script>
export default {
  props: {
    value: {
      type: Number,
      required: true,
    },
  },
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    increment() {
      this.count += 1;
    },
  },
};
</script>

// frameworks/react/src/scenario-2/Cell.js
import React from "react";

export default class Cell extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
    };
  }

  increment() {
    this.setState({
      count: this.state.count + 1,
    });
  }

  render() {
    return (
      <span>
        Prop value: {this.props.value}, internal value: {this.state.count}
        <button class="cell-btn-increment" onClick={() => this.increment()}>
          Update child
        </button>
      </span>
    );
  }
}
