// frameworks/svelte/src/scenario-2/Row.svelte
<script>
import Cell from "./Cell.svelte";

export let columns;
let count = 0;
let offset = 0;

function onInput() {
    count += 1;
}
function updateRow() {
    offset += 1;
}

</script>

  <div>
    <div>
      Row count: { count }
      <button class="row-btn-update-children" on:click="{updateRow}">
        Update children
      </button>
      <button class="row-btn-update-self" on:click="{onInput}">Upate parent</button>
    </div>
    {#each columns as column, i (column.id)}
        <Cell value="{i + offset}" />
    {/each}    
  </div>

// frameworks/react/src/scenario-2/Row.js
import React from "react";

import Cell from "./Cell.js";

export default class Row extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
      offset: 0,
    };
  }

  onInput() {
    this.setState({
      count: this.state.count + 1,
    });
  }

  updateRow() {
    this.setState({
      offset: this.state.offset + 1,
    });
  }

  render() {
    return (
      <div>
        <div>
          Row count: {this.state.count}
          <button
            class="row-btn-update-children"
            onClick={() => this.updateRow()}
          >
            Update children
          </button>
          <button class="row-btn-update-self" onClick={() => this.onInput()}>
            Upate parent
          </button>
        </div>
        {this.props.columns.map((column, i) => (
          <Cell key={column.id} value={i + this.state.offset} />
        ))}
      </div>
    );
  }
}
